// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pppbpgywfzqjnzfmfzme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwcGJwZ3l3Znpxam56Zm1mem1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTQzODMsImV4cCI6MjA2NzAzMDM4M30.Bb--utOgH2l8Ojeijj8frcIeedKSMep3JCGvXP1YJ3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});